In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from lxml import html
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

IMPORTED THE NECESSARY LIBRARIES FOR WEB SCRAPING.

## ANSWER TO QUESTION 1  OF WEB SCRAPING ASSIGNMENT 4:-

In [8]:
driver = webdriver.Chrome('chromedriver.exe')

In [9]:
url = 'https://en.wikipedia.org/wiki/'
driver.get(url)
time.sleep(5)

In [10]:
driver.find_element_by_xpath('//input[@title="Search Wikipedia [alt-shift-f]"]').click()
time.sleep(2)
driver.find_element_by_xpath('//input[@title="Search Wikipedia [alt-shift-f]"]').send_keys('List of most-viewed Youtube videos')
time.sleep(2)
driver.find_element_by_xpath('//input[@id="searchButton"]').click()
time.sleep(2)

In [11]:
url3="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
page = requests.get(url3)
soup=BeautifulSoup(page.text,'lxml')
table = driver.find_element_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']")
table.find_elements_by_xpath("//th[@class='headerSort']")

headers=[]
for i in table.find_elements_by_xpath("//th[@class='headerSort']"):
    headers.append(i.text)
headers
df=pd.DataFrame(columns=headers)
df=df.iloc[:,:5]
df

Empty DataFrame
Columns: [No., Video name, Uploader, Views (billions), Upload date]
Index: []

In [12]:
rank=[]
name=[]
upl=[]
v=[]
date=[]


rs = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]")
for i in rs:
    try:
        rank.append(i.text)
    except NoSuchElementException:
        rank.append("-")
rank=rank[:30]
rank
n = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
for i in n:
    try:
        name.append(i.text)
    except NoSuchElementException:
        name.append("-") 
name=name[:30]
name
uplo = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
for i in uplo:
    try:
        upl.append(i.text)
    except NoSuchElementException:
        upl.append("-") 
upl=upl[:30]
upl
ve = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
for i in ve:
    try:
        v.append(i.text)
    except NoSuchElementException:
        v.append("-") 
v=v[:30]
v
dt = driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")
for i in dt:
    try:
        date.append(i.text)
    except NoSuchElementException:
        date.append("-") 
date=date=date[:30]
pd.set_option('display.max_colwidth', None)
video_data=pd.DataFrame({'RANK':rank,'VIDEO_NAME':name,'ARTIST':upl,'VIEWS':v,'UPLOAD_DATE':date,})
video_data

,RANK,VIDEO_NAME,ARTIST,VIEWS,UPLOAD_DATE
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,8.91,"June 17, 2016"
1,2.,"""Despacito""[24]",Luis Fonsi,7.43,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,5.53,"October 8, 2016"
3,4.,"""Shape of You""[26]",Ed Sheeran,5.37,"January 30, 2017"
4,5.,"""See You Again""[27]",Wiz Khalifa,5.16,"April 6, 2015"
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,4.44,"January 31, 2012"
6,7.,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,4.26,"May 2, 2018"
7,8.,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,4.22,"February 27, 2018"
8,9.,"""Uptown Funk""[33]",Mark Ronson,4.22,"November 19, 2014"
9,10.,"""Gangnam Style""[34]",Psy,4.11,"July 15, 2012"
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,3.97,"March 6, 2014"
11,12.,"""Sugar""[37]",Maroon 5,3.50,"January 14, 2015"
12,13.,"""Sorry""[38]",Justin Bieber,3.45,"October 22, 2015"
13,14.,"""Dame Tu Cosita""[39]",El Chombo,3.43,"April 5, 2018"
14,15.,"""Roar""[40]",Katy Perry,3.38,"September 5, 2013"
15,16.,"""Counting Stars""[41]",OneRepublic,3.33,"May 31, 2013"
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,3.28,"October 7, 2014"
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,3.13,"May 24, 2018"
18,19.,"""Dark Horse""[44]",Katy Perry,3.10,"February 20, 2014"
19,20.,"""Faded""[45]",Alan Walker,3.09,"December 3, 2015"
20,21.,"""Shake It Off""[46]",Taylor Swift,3.07,"August 18, 2014"
21,22.,"""Girls Like You""[47]",Maroon 5,3.06,"May 31, 2018"
22,23.,"""Lean On""[48]",Major Lazer,3.06,"March 22, 2015"
23,24.,"""Bailando""[49]",Enrique Iglesias,3.06,"April 11, 2014"
24,25.,"""Let Her Go""[50]",Passenger,3.02,"July 25, 2012"
25,26.,"""Mi Gente""[51]",J Balvin,2.94,"June 29, 2017"
26,27.,"""Perfect""[52]",Ed Sheeran,2.89,"November 9, 2017"
27,28.,"""Waka Waka (This Time for Africa)""[53]",Shakira,2.87,"June 4, 2010"
28,29.,"""Axel F""[54]",Crazy Frog,2.86,"June 16, 2009"
29,30.,"""Hello""[55]",Adele,2.85,"October 22, 2015"

## ANSWER TO QUESTION 2 OF WEB SCRAPING ASSIGNMENT 4:-

In [2]:
driver2 = webdriver.Chrome('chromedriver.exe')

In [3]:
url_ = 'https://www.bcci.tv/'
driver2.get(url_)
time.sleep(5)

In [4]:
driver2.find_element_by_xpath('//div[@class="navigation__drop-down drop-down drop-down--reveal-on-hover"]').click()
time.sleep(2)

In [5]:
driver2.find_element_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]').click()
time.sleep(2)

In [6]:
title=[]
series=[]
place=[]
TIME=[]
date=[]


t = driver2.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
for i in t:
    try:
        title.append(i.text)
    except NoSuchElementException:
        title.append("-")
title
s = driver2.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
for i in s:
    try:
        series.append(i.text)
    except NoSuchElementException:
        series.append("-") 
series
pl = driver2.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
for i in pl:
    try:
        place.append(i.text)
    except NoSuchElementException:
        place.append("-") 
place
ti = driver2.find_elements_by_xpath("//span[@class='fixture__time']")
for i in ti:
    try:
        TIME.append(i.text)
    except NoSuchElementException:
        TIME.append("-") 
TIME
dt = driver2.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']")
for i in dt:
    try:
        date.append(i.text.replace("\n",","))
    except NoSuchElementException:
        date.append("-") 

pd.set_option('display.max_colwidth', None)
fixtures_data=pd.DataFrame({'TITLE':title,'SERIES':series,'PLACE':place,'TIME':TIME,'DATE':date})
fixtures_data

,TITLE,SERIES,PLACE,TIME,DATE
0,1st ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",14:30 IST,"Tuesday,13,JULY,14:30 IST"
1,2nd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",14:30 IST,"Friday,16,JULY,14:30 IST"
2,3rd ODI,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",14:30 IST,"Sunday,18,JULY,14:30 IST"
3,1st T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",19:00 IST,"Wednesday,21,JULY,19:00 IST"
4,2nd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",19:00 IST,"Friday,23,JULY,19:00 IST"
5,3rd T20I,SRI LANKA V INDIA 2021,"R Premadasa Stadium, Colombo",19:00 IST,"Sunday,25,JULY,19:00 IST"
6,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",15:30 IST,"Wednesday,04,AUGUST,15:30 IST"
7,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",15:30 IST,"Thursday,12,AUGUST,15:30 IST"
8,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",15:30 IST,"Wednesday,25,AUGUST,15:30 IST"
9,4th Test,ENGLAND V INDIA 2021,"The Oval, London",15:30 IST,"Thursday,02,SEPTEMBER,15:30 IST"
10,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",15:30 IST,"Friday,10,SEPTEMBER,15:30 IST"

## ANSWER TO QUESTION 3 OF WEB SCRAPING ASSIGNMENT 4:-

In [70]:
driver3 = webdriver.Chrome('chromedriver.exe')

In [71]:
url11 = 'https://www.guru99.com/'
driver3.get(url11)
time.sleep(5)

In [72]:
driver3.find_element_by_xpath('//td[@id="gs_tti51"]/input').click()
time.sleep(2)

In [73]:
driver3.find_element_by_xpath('//td[@id="gs_tti51"]/input').send_keys('selenium exception handling')
time.sleep(2)

In [74]:
driver3.find_element_by_xpath('//*[@id="___gcse_1"]/div/div/form/table/tbody/tr/td[2]/button').click()
time.sleep(2)

In [81]:
driver3.find_element_by_xpath('//*[@id="___gcse_1"]/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a/b').click()
time.sleep(2)

In [80]:
usrl = "https://www.guru99.com/exception-handling-selenium.html"
page = requests.get(usrl)
soup=BeautifulSoup(page.text,'lxml')
table = soup.find('table',class_='table table-striped')
exception=pd.DataFrame(columns=['Exception name','Description'])
exception
pd.set_option('display.max_colwidth', None)
for j in table.find_all('tr')[1:]:
    rows=j.find_all('td')
    row = [tr.text.replace('\n','') for tr in rows]
    length = len(exception)
    exception.loc[length]=row
    exception.loc[length]
exception

,Exception name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.
1,ElementNotSelectableException,"This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact."
2,NoSuchElementException,This Exception occurs if an element could not be found.
3,NoSuchFrameException,This Exception occurs if the frame target to be switched to does not exist.
4,NoAlertPresentException,This Exception occurs when you switch to no presented alert.
5,NoSuchWindowException,This Exception occurs if the window target to be switch does not exist.
6,StaleElementReferenceException,This Selenium exception occurs happens when the web element is detached from the current DOM.
7,SessionNotFoundException,The WebDriver is acting after you quit the browser.
8,TimeoutException,"Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn't found in the specified time."
9,WebDriverException,This Exception takes place when the WebDriver is acting right after you close the browser.
10,ConnectionClosedException,This type of Exception takes place when there is a disconnection in the driver.
11,ElementClickInterceptedException,The command may not be completed as the element receiving the events is concealing the element which was requested clicked.
12,ElementNotInteractableException,"This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element."
13,ErrorInResponseException,This happens while interacting with the Firefox extension or the remote driver server.
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if the server returns an error without a stack trace.
15,ImeActivationFailedException,This expectation will occur when IME engine activation has failed.
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.
18,InvalidArgumentException,It occurs when an argument does not belong to the expected type.
19,InvalidCookieDomainException,This happens when you try to add a cookie under a different domain instead of current URL.
20,InvalidCoordinatesException,This type of Exception matches an interacting operation that is not valid.
21,InvalidElementStateExceptio,It occurs when command can't be finished when the element is invalid.
22,InvalidSessionIdException,This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.
23,InvalidSwitchToTargetException,This occurs when the frame or window target to be switched does not exist.
24,JavascriptException,This issue occurs while executing JavaScript given by the user.
25,JsonException,It occurs when you afford to get the session when the session is not created.
26,NoSuchAttributeException,This kind of Exception occurs when the attribute of an element could not be found.
27,MoveTargetOutOfBoundsException,"It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document."
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.
30,NotFoundException,This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.
31,RemoteDriverServerException,This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be successfully created.
34,UnableToSetCookieException,This occurs if a driver is unable to set a cookie.
35,UnexpectedTagNameException,Happens if a support class did not get a web element as expected.
36,UnhandledAlertException,"This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation."
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an unexpected alert.
38,UnknownMethodException,This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.
39,UnreachableBrowserException,This Exception occurs only when the browser is not able to be opened or crashed because of some reason.
40,UnsupportedCommandException,This occurs when remote WebDriver does n't send valid commands as expected.

## ANSWER TO QUESTION 4 OF WEB SCRAPING ASSIGNMENT 4:-

In [4]:
drivers = webdriver.Chrome('chromedriver.exe')

In [5]:
ur = 'http://statisticstimes.com/'
drivers.get(ur)
time.sleep(5)

In [6]:
drivers.find_element_by_xpath('//div[@class="navbar"]/div[2]').click()
time.sleep(2)

drivers.find_element_by_xpath('//div[@class="dropdown-content"]/a[3]').click()
time.sleep(2)

In [7]:
drivers.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(2)

In [8]:
rank=[]
state=[]
GSDP_Cr_INR_at_Current_prices_19_20=[]
GSDP_Cr_INR_at_Current_prices_18_19=[]
share_18_19=[]
GDP_billion_2019=[]

rs = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[1]")
for i in rs:
    try:
        rank.append(i.text)
    except NoSuchElementException:
        rank.append("-")

n = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[2]")
for i in n:
    try:
        state.append(i.text)
    except NoSuchElementException:
        state.append("-") 

uplo = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[3]")
for i in uplo:
    try:
        GSDP_Cr_INR_at_Current_prices_19_20.append(i.text)
    except NoSuchElementException:
        GSDP_Cr_INR_at_Current_prices_19_20.append("-") 

ve = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[4]")
for i in ve:
    try:
        GSDP_Cr_INR_at_Current_prices_18_19.append(i.text)
    except NoSuchElementException:
        GSDP_Cr_INR_at_Current_prices_18_19.append("-") 


sh = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[5]")
for i in sh:
    try:
        share_18_19.append(i.text)
    except NoSuchElementException:
        share_18_19.append("-") 
        
dt = drivers.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[6]")
for i in dt:
    try:
        GDP_billion_2019.append(i.text)
    except NoSuchElementException:
        GDP_billion_2019.append("-") 


pd.set_option('display.max_colwidth', None)
gdp_data=pd.DataFrame({'RANK':rank,'STATE':state,'GSDP_Cr_INR_at_Current_prices_19_20':GSDP_Cr_INR_at_Current_prices_19_20,'GSDP_Cr_INR_at_Current_prices_18_19':GSDP_Cr_INR_at_Current_prices_18_19,'SHARE_18_19':share_18_19,'GDP_BILLIONS_$_2019':GDP_billion_2019})
gdp_data

,RANK,STATE,GSDP_Cr_INR_at_Current_prices_19_20,GSDP_Cr_INR_at_Current_prices_18_19,SHARE_18_19,GDP_BILLIONS_$_2019
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

## ANSWER TO QUESTION 5 OF WEB SCRAPING ASSIGNMENT 4:-

In [3]:
gdriver = webdriver.Chrome('chromedriver.exe')

In [4]:
gurl = 'https://github.com/'
gdriver.get(gurl)
time.sleep(3)

In [5]:
gdriver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary').click()
time.sleep(2)

gdriver.find_element_by_xpath('//div[@class="dropdown-menu flex-auto rounded px-0 pt-2 pb-0 mt-0 pb-4 p-lg-4 position-relative position-lg-absolute left-0 left-lg-n4"]/ul[2]/li[3]/a').click()
time.sleep(2)

In [6]:
#searching for urls for first 3 pages for guitars--
urls=[]

github_urls=gdriver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")  
for i in github_urls:
    urls.append(i.get_attribute('href'))



urls

['https://github.com/chefyuan/algorithm-base',
 'https://github.com/trekhleb/javascript-algorithms',
 'https://github.com/airbnb/javascript',
 'https://github.com/30-seconds/30-seconds-of-code',
 'https://github.com/earthly/earthly',
 'https://github.com/nvm-sh/nvm',
 'https://github.com/microsoft/IoT-For-Beginners',
 'https://github.com/bndw/wifi-card',
 'https://github.com/austinsonger/Incident-Playbook',
 'https://github.com/ryanmcdermott/clean-code-javascript',
 'https://github.com/lydiahallie/javascript-questions',
 'https://github.com/sorrycc/awesome-javascript',
 'https://github.com/jaywcjlove/awesome-mac',
 'https://github.com/go-kratos/kratos',
 'https://github.com/laynH/Anime-Girls-Holding-Programming-Books',
 'https://github.com/swisskyrepo/PayloadsAllTheThings',
 'https://github.com/goldbergyoni/nodebestpractices',
 'https://github.com/shufflewzc/faker2',
 'https://github.com/rosinality/alias-free-gan-pytorch',
 'https://github.com/fenixsoft/awesome-fenix',
 'https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch',
 'https://github.com/TheAlphamerc/flutter_ecommerce_app',
 'https://github.com/facebook/folly',
 'https://github.com/ailabstw/social-distancing-ios',
 'https://github.com/Vishal-raj-1/Awesome-JavaScript-Projects']

In [10]:
Repository_title=[]
Repository_description=[]
Number_of_Contributors=[]
Language_used=[]


for ur in urls:

    gdriver.get(ur)

    time.sleep(2)

    try:

        name = gdriver.find_element_by_xpath("//span[@class='author flex-self-stretch']")

        Repository_title.append(name.text)

    except NoSuchElementException:

        Repository_title.append("-")

    try:
        desc_tag=gdriver.find_element_by_xpath("//div[@class='BorderGrid-cell']")
        Repository_description.append(desc_tag.text.replace("\n"," "))
    except NoSuchElementException:
        Repository_description.append('-')

    try:
        nr=gdriver.find_element_by_xpath("//div[@class='BorderGrid BorderGrid--spacious']/div[3]/div/h2/a")
        Number_of_Contributors.append(nr.text)
    except NoSuchElementException:
        Number_of_Contributors.append('-')  
    
    try:
        l_tags=gdriver.find_element_by_xpath("//div[@class='BorderGrid BorderGrid--spacious']/div[4]/div/ul")
        Language_used.append(l_tags.text.replace("\n",","))
    except NoSuchElementException:
        Language_used.append('-')


    
#creating a dataframe
pd.set_option('display.max_colwidth', None)
df=pd.DataFrame({'Repository_title':Repository_title,'Repository_description':Repository_description,'Number_of_contributors':Number_of_Contributors,
                'Language_used':Language_used})
#printing dataframe
df

,Repository_title,Repository_description,Number_of_contributors,Language_used
0,chefyuan,About 专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！ Topics java algorithms leetcode offer interview-practice interview-questions programmers base Resources Readme License MIT License,Packages,-
1,trekhleb,About 📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings Topics javascript computer-science algorithm algorithms interview data-structures interview-preparation javascript-algorithms Resources Readme License MIT License,-,-
2,airbnb,About JavaScript Style Guide Topics javascript styleguide eslint es6 style-linter linting style-guide es2015 naming-conventions arrow-functions es2017 es2016 tc39 es2018 Resources Readme License MIT License,Packages,-
3,30-seconds,About Short JavaScript code snippets for all your development needs www.30secondsofcode.org/js/p/1 Topics nodejs javascript education snippets programming es6-javascript learn-to-code awesome-list snippets-collection learning-resources Resources Readme License CC0-1.0 License,Contributors 259,"JavaScript,100.0%"
4,earthly,About Build automation for the container era earthly.dev Topics dockerfiles build build-automation docker-images hacktoberfest reproducible-builds container-builder hacktoberfest2020 Resources Readme License View license,-,
5,nvm-sh,About Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions Topics nodejs shell bash zsh node install nvm posix lts version-manager node-js posix-compliant nvmrc Resources Readme License MIT License,-,-
6,microsoft,"About 12 Weeks, 24 Lessons, IoT for All! Topics python raspberry-pi iot rpi microcontroller cpp iot-device iot-edge wio-terminal Resources Readme License MIT License",Contributors 25,"C++,49.8%,Python,39.2%,C,3.9%,Jupyter Notebook,2.1%,Vue,2.1%,HTML,2.0%,JavaScript,0.9%"
7,bndw,About 📶 Print a QR code for connecting to your WiFi wificard.io Topics react wifi Resources Readme License MIT License,-,-
8,austinsonger,About GOAL: Incident Response Playbooks Mapped to MITRE Attack Tactics and Techniques. [Contributors Friendly] austinsonger.github.io/incident-playbook/ Topics catalog incident-response playbook cybersecurity mitre incident-management incidents contributions-welcome mitre-attack contributors-welcome cybersecurity-playbook Resources Readme License MIT License,-,"austinsonger Austin Songer,gitter-badger The Gitter Badger,sn0b4ll Dominik Sigl,cclauss Christian Clauss"
9,ryanmcdermott,About 🛁 Clean Code concepts adapted for JavaScript Topics javascript best-practices clean-code composition inheritance clean-architecture principles Resources Readme License MIT License,Packages,-
10,lydiahallie,"About A long list of (advanced) JavaScript questions, and their explanations ✨ Resources Readme License MIT License",Packages,-
11,sorrycc,"About 🐢 A collection of awesome browser-side JavaScript libraries, resources and shiny things. Resources Readme",Packages,
12,jaywcjlove,"About  Now we have become very big, Different from the original idea. Collect premium software in various categories. git.io/macx Topics macos mac list apple awesome software macosx awesome-list mac-osx awesome-lists Resources Readme License CC0-1.0 License",-,-
13,go-kratos,About A Go framework for microservices. go-kratos.dev Topics go golang http library microservices framework protobuf toolkit rest-api architecture generate grpc kratos Resources Readme License MIT License,-,-
14,laynH,About Anime Girls Holding Programming Books Topics anime Resources Readme,Packages,-
15,swisskyrepo,About A list of useful payloads and bypass for Web Application Security and Pentest/CTF Topics security hacking web-application cheatsheet enumeration penetration-testing bounty vulnerability methodology bugbounty pentest bypass payload payloads hacktoberfest privilege-escalation redteam Resources Readme License MIT License,-,
16,goldbergyoni,About ✅ The Node.js best practices list (June 2021) twitter.com/nodepractices/ Topics nodejs javascript testing npm styleguide express microservices rest mocha types eslint es6 jest style-guide best-practices expressjs node-js nodejs-development Resources Readme License CC-BY-SA-4.0 License,-,-
17,shufflewzc,About 不知名大佬备份 Resources Readme,Packages,-
18,rosinality,About Unofficial implementation of Alias-Free Generative Adversarial Networks. (https://arxiv.org/abs/2106.12423) in PyTorch Topics gan stylegan2 alias-free-gan Resources Readme License MIT License,Packages,-
19,fenixsoft,About 讨论如何构建一套可靠的大型分布式系统 icyfenix.cn Topics kubernetes microservice architecture cloud-native springcloud istio Resources Readme,Contributors 8,"Vue,53.4%,JavaScript,40.7%,Stylus,4.7%,Shell,1.2%"
20,mikel-brostrom,About Real-time multi-object tracker using YOLO v5 and deep sort Topics real-time video pytorch computer-camera rtsp-stream web-camera you-only-look-once pedestrian-tracking deep-sort http-stream multple-object-tracking deep-association-metric yolov5 simple-online-and-realtime-tracking pytorch-yolov5 yolo-v5 Resources Readme License GPL-3.0 License,Packages,-
21,TheAlphamerc,About E-Commerce App built in flutter Topics flutter flutter-apps flutter-demo flutter-examples flutter-ui flutter-app Resources Readme License BSD-2-Clause License,Packages,-
22,facebook,About An open-source C++ library developed and used at Facebook. groups.google.com/forum/?fromgroups#!forum/facebook-folly Resources Readme License Apache-2.0 License,Packages,-
23,ailabstw,About Taiwan Social Distancing App - iOS apps.apple.com/tw/app/%e8%87%ba%e7%81%a3%e7%a4%be%e4%ba%a4%e8%b7%9d%e9%9b%a2/id1554431836 Resources Readme License MIT License,Packages,-
24,Vishal-raj-1,About This Repository contain awesome vanilla JavaScript projects. vishal-raj-1.github.io/awesome-javascript-projects/ Topics javascript bootstrap html5 css3 vanilla-javascript vanila-js Resources Readme License MIT License,Contributors 234,"JavaScript,49.0%,HTML,30.5%,CSS,20.0%,SCSS,0.5%"

## ANSWER TO QUESTION 6 OF WEB SCRAPING ASSIGNMENT 4:-

In [13]:
bdriver = webdriver.Chrome('chromedriver.exe')

In [14]:
burl = 'https://www.billboard.com/'
bdriver.get(burl)
time.sleep(3)

In [15]:
bdriver.find_element_by_xpath("//nav[@class='header__subnav bg--light']/ul/li[3]").click()
time.sleep(2)

In [33]:
song_name=[]
artist=[]
last_week_rank=[]
peak_rank=[]
weeks_on_board=[]





ns = bdriver.find_elements_by_xpath("//li[@class='chart-list__element display--flex']/button/span[2]/span[1]")
for i in ns:
    song_name.append(i.text.replace("\n",""))

    

a_tag=bdriver.find_elements_by_xpath("//li[@class='chart-list__element display--flex']/button/span[2]/span[2]")
for i in a_tag:
    artist.append(i.text.replace("\n",""))





nr=bdriver.find_elements_by_xpath("//li[@class='chart-list__element display--flex']/button/div[1]/div[2]")
for i in nr:
    last_week_rank.append(i.text.replace("\n",""))




pr_tags=bdriver.find_elements_by_xpath("//li[@class='chart-list__element display--flex']/button/div[1]/div[3]")
for u in pr_tags:
    peak_rank.append(u.text.replace("\n",""))


wob_tags=bdriver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for t in wob_tags:
    try:
        weeks_on_board.append(t.text)
    except NoSuchElementException:
        weeks_on_board.append("-")
weeks_on_board

    
#creating a dataframe
pd.set_option('display.max_colwidth', None)
df_s=pd.DataFrame({'Song_name':song_name,'Artist_Name':artist,'Last_week_rank':last_week_rank,
                'Peak_rank':peak_rank,'Weeks_on_board':weeks_on_board})
#printing dataframe
df_s

,Song_name,Artist_Name,Last_week_rank,Peak_rank,Weeks_on_board
0,Butter,BTS,1,1,6
1,Good 4 U,Olivia Rodrigo,2,1,7
2,Kiss Me More,Doja Cat Featuring SZA,4,3,12
3,Levitating,Dua Lipa Featuring DaBaby,2,39,39
4,Bad Habits,Ed Sheeran,-,5,1
...,...,...,...,...,...
95,Twerkulator,City Girls,96,51,4
96,Tombstone,Rod Wave,11,14,14
97,Miss The Rage,Trippie Redd & Playboi Carti,11,8,8
98,Rise!,"Tyler, The Creator Featuring Daisy World",-,99,1
99,Working,Tate McRae X Khalid,94,2,2

## ANSWER TO QUESTION 7 OF WEB SCRAPING ASSIGNMENT 4:-

In [2]:
ndriver = webdriver.Chrome('chromedriver.exe')

In [3]:
nurl = 'https://www.naukri.com/hr-recruiters-consultants'
ndriver.get(nurl)
time.sleep(3)

In [4]:
ndriver.find_element_by_xpath("//input[@placeholder='Skills, Designations, Companies']") 
ndriver.find_element_by_xpath("//input[@placeholder='Skills, Designations, Companies']").send_keys("Data Science")

In [5]:
ndriver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

In [14]:
name=[]
design=[]
company=[]
skills=[]
location=[]


n_tags=ndriver.find_elements_by_xpath("//div[@class='vcard']/p/a/span[1]")
for i in n_tags:
    try:
        name.append(i.text)

    except NoSuchElementException:
        name.append("-")


d_tags=ndriver.find_elements_by_xpath("//span[@class='ellipsis clr']")
for i in d_tags:
    try:
        design.append(i.text)

    except NoSuchElementException:
        design.append("-")


c_tags=ndriver.find_elements_by_xpath("//div[@class='vcard']/p/a[2]")
for i in c_tags:
    try:
        company.append(i.text)

    except NoSuchElementException:
        company.append("-")

        
s_tags=ndriver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for i in s_tags:
    try:
        skills.append(i.text)

    except NoSuchElementException:
        skills.append("-")
        
l_tags = ndriver.find_elements_by_xpath("//div[@class='vcard']/p/span[2]")
for i in l_tags:
    try:
        location.append(i.text)

    except NoSuchElementException:
        location.append("-")
location.insert(26,"-")
location.insert(-2,"-")
location

#creating a dataframe
pd.set_option('display.max_colwidth', None)
df_n=pd.DataFrame({'Name':name,'Designation':design,'Company':company,
                'Skills required':skills,'Location':location})
#printing dataframe
df_n

,Name,Designation,Company,Skills required,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine Learning, Business Analytics",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human",Mumbai
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning",Pune
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager",Hyderabad / Secunderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing",Navi Mumbai
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship",Delhi
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining",Hyderabad / Secunderabad
20,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop",Pune
21,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine Learning, Data Analytics",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology",Pune
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js",Bengaluru / Bangalore
25,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data",Bengaluru / Bangalore
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data",-
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture",Delhi
28,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi",Bengaluru / Bangalore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience",Mysoru / Mysore
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All",Hyderabad / Secunderabad
32,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learning, Data Science",Bengaluru / Bangalore
33,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced",Noida
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java",New Delhi
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written",Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview",Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql",MYSORE
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Computer Science, Communication Skills",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing",-
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational Sales, Institutional Sales, pmp, Data Science, Business Development, Revenue Generation, Sales Achievement, new",Noida
49,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical Management, Financial Management, Human Resource Management, Banking, Google Adwords, Business Analysis, It",Mumbai

## ANSWER TO QUESTION 8 OF WEB SCRAPING ASSIGNMENT 4:-

In [39]:
driverb = webdriver.Chrome('chromedriver.exe')

In [41]:
Url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driverb.get(Url)
time.sleep(3)

In [47]:
page = requests.get(Url)
soup=BeautifulSoup(page.text,'lxml')
table = soup.find('table',class_='in-article sortable')
table.find_all('th')


headers=[]
for i in table.find_all('th'):
    headers.append(i.text.replace("\n",""))
headers
df_books=pd.DataFrame(columns=headers)
df_books

Empty DataFrame
Columns: [             Rank             ,              Title             ,              Author             ,              Volume Sales             ,              Publisher             ,              Genre             ]
Index: []

In [50]:
rank=[]
title=[]
author=[]
vol=[]
publisher=[]
genre=[]

rs = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[1]")
for i in rs:
    try:
        rank.append(i.text)
    except NoSuchElementException:
        rank.append("-")

n = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
for i in n:
    try:
        title.append(i.text)
    except NoSuchElementException:
        title.append("-") 

uplo = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
for i in uplo:
    try:
        author.append(i.text)
    except NoSuchElementException:
        author.append("-") 

ve = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
for i in ve:
    try:
        vol.append(i.text)
    except NoSuchElementException:
        vol.append("-") 


sh = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
for i in sh:
    try:
        publisher.append(i.text)
    except NoSuchElementException:
        publisher.append("-") 
        
dt = driverb.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
for i in dt:
    try:
        genre.append(i.text)
    except NoSuchElementException:
        genre.append("-") 


pd.set_option('display.max_colwidth', None)
books_data=pd.DataFrame({'RANK':rank,'TITLE':title,'AUTHOR':author,'VOLUME_SALES':vol,'PUBLISHER':publisher,'GENRE':genre})
books_data

,RANK,TITLE,AUTHOR,VOLUME_SALES,PUBLISHER,GENRE
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the Love of a Family","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## ANSWER TO QUESTION 9 OF WEB SCRAPING ASSIGNMENT 4:-

In [2]:
idriver = webdriver.Chrome('chromedriver.exe')

In [5]:
iurl = 'https://www.imdb.com/list/ls095964455/'
idriver.get(iurl)
time.sleep(3)

In [18]:
name=[]
names_tags= idriver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
for i in names_tags:
    name.append(i.text)


years=[]
ys=idriver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
for i in ys:
    years.append(i.text)


genres=[]
gen= idriver.find_elements_by_xpath("//span[@class='genre']")
for i in gen:
    genres.append(i.text)


runtime=[]
rt= idriver.find_elements_by_xpath("//span[@class='runtime']")
for i in rt:
    runtime.append(i.text)



ratings=[]
rating_tag= idriver.find_elements_by_xpath("//div[@class='ipl-rating-widget']/div/span[2]")
for i in rating_tag:
    ratings.append(i.text)


votes=[]
vt= idriver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]")
for i in vt:
    votes.append(i.text.replace("Votes: ",""))
votes

pd.set_option('display.max_colwidth', None)
imdb_data=pd.DataFrame({'NAME':name,'YEAR_SPAN':years,'GENRE':genres,'RUNTIME':runtime,'RATINGS':ratings,'VOTES':votes})
imdb_data

,NAME,YEAR_SPAN,GENRE,RUNTIME,RATINGS,VOTES
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,834,494"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"873,275"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"878,887"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"264,096"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"225,625"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,776"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,379"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"169,432"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"35,112"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"193,225"

## ANSWER TO QUESTION 10 OF WEB SCRAPING ASSIGNMENT 4:-

In [2]:
mldriver = webdriver.Chrome('chromedriver.exe')

In [3]:
mlurl = 'https://archive.ics.uci.edu/'
mldriver.get(mlurl)
time.sleep(3)

In [4]:
mldriver.find_element_by_xpath("//span[@class='whitetext']/a/font/b").click()

In [24]:
name=[]
names_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[2]/p/b/a")
for i in names_tag:
    name.append(i.text)
len(name)

dty=[]
dty_tag= mldriver.find_elements_by_xpath("//table[@cellpadding='5']/tbody/tr/td[2]/p")[1:]
for i in dty_tag:
    try:
        dty.append(i.text)
    except NoSuchElementException:
        dty.append("-")
len(dty)

task=[]
t_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[3]/p")[1:]
for i in t_tag:
    try:
        task.append(i.text)
    except NoSuchElementException:
        task.append("-")
tasks=task[:-1]

attrs=[]
attr_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[4]/p")[1:]
for i in attr_tag:
    attrs.append(i.text)
attrs

noi=[]
noi_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[5]/p")[1:]
for i in noi_tag:
    noi.append(i.text)
noi

noa=[]
noa_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[6]/p")[1:]
for i in noa_tag:
    noa.append(i.text)
noa

years=[]
y_tag= mldriver.find_elements_by_xpath("//table/tbody/tr/td[7]/p")[1:]
for i in y_tag:
    try:
        years.append(i.text)
    except NoSuchElementException:
        years.append("-")
years

ml_data=pd.DataFrame({'NAME':name,'DATATYPE':dty,'TASK':tasks,'ATTRIBUTE_TYPE':attrs,'NUMBER_OF_INSTANCES':noi,'NUMBER_OF_ATTRIBUTES':noa,'YEAR':years})
ml_data

,NAME,DATATYPE,TASK,ATTRIBUTE_TYPE,NUMBER_OF_INSTANCES,NUMBER_OF_ATTRIBUTES,YEAR
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021